# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotshake < Formula
  desc "P2P mesh network using WireGuard"
  homepage "https://dotshake.com/"
  version "0.0.28"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.28/dotshake_0.0.28_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "98e4db1f80d42d291d3a956788f9fe85e40a208cb2b8bfd1c0fe2603c1ea3205"

      def install
        bin.install "dotshake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.28/dotshake_0.0.28_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e5797ae4cb8a0b7aea92733f3853e2d8ba2919f6586951cc482180ae5c9d3642"

      def install
        bin.install "dotshake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.28/dotshake_0.0.28_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ef671b1a778443a5d6610fc85275058699b558bbf5aba2e9b38a30390f0242cd"

      def install
        bin.install "dotshake"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.28/dotshake_0.0.28_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "b1441af606c6d6b5dff5c810fa3bbe67c9e85b6958e6c94c0653d1af3db67926"

      def install
        bin.install "dotshake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.28/dotshake_0.0.28_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5188dc40b86879840cca4fb6fc7e14742fee9fe56f0172fd77f8fb2893a69b7b"

      def install
        bin.install "dotshake"
      end
    end
  end

  test do
    system "#{bin}/dotshake version"
  end
end
