# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotshaker < Formula
  desc "P2P mesh network using WireGuard"
  homepage "https://dotshake.com/"
  version "0.0.18"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.18/dotshaker_0.0.18_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7fdbaf47d71672cba8f0355575eaf1575b22f8e19a7de214223ebc75b03da543"

      def install
        bin.install "dotshaker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.18/dotshaker_0.0.18_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "58e142cf3e7de50c87b7da03362a8aa27ae0bb4f9b9bc0b540a3702eeb47140c"

      def install
        bin.install "dotshaker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.18/dotshaker_0.0.18_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "916c78e17508f93cb8beab4b1e7185dd0a0b68d36051f55d5ad112dc3b1c4220"

      def install
        bin.install "dotshaker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.18/dotshaker_0.0.18_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e2f32982dc42356cbda1ff170ac150998511382adf7ee2569f37dbe009d53a70"

      def install
        bin.install "dotshaker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Notch-Technologies/dotshake/releases/download/v0.0.18/dotshaker_0.0.18_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0be50f8fc0b522bbc85b9651fc687d965be12d806457a8645df2d2225ef96230"

      def install
        bin.install "dotshaker"
      end
    end
  end

  test do
    system "#{bin}/dotshaker version"
  end
end
